development:
  sessions:
    default:
      database: patient_data_server_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: patient_data_server_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017

production:
  sessions:
    default:
      database: patient_data_server_production
      hosts:
        - localhost:27017